let voices = [];

function loadVoices() {
    voices = speechSynthesis.getVoices();
}

loadVoices();

if (speechSynthesis.onvoiceschanged !== undefined) {
    speechSynthesis.onvoiceschanged = loadVoices;
}const state={stars:Number(localStorage.getItem("alice-stars")||0),currentSyllable:"MA",target:34,selectedTen:null,selectedUnit:null};
const syllables=["MA","ME","MI","MO","MU","LA","LE","LI","LO","LU","SA","SE","SI","SO","SU"];
const el={stars:document.querySelector("#stars"),garden:document.querySelector("#garden"),readingPrompt:document.querySelector("#readingPrompt"),readingChoices:document.querySelector("#readingChoices"),readingMessage:document.querySelector("#readingMessage"),targetNumber:document.querySelector("#targetNumber"),tens:document.querySelector("#tens"),units:document.querySelector("#units"),assembled:document.querySelector("#assembled"),numberMessage:document.querySelector("#numberMessage")};
function speak(text){if(!("speechSynthesis" in window)){alert("La voix n'est pas disponible dans ce navigateur.");return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="fr-FR";u.rate=.88;u.pitch=1.35;speechSynthesis.speak(u)}
function numberToFrench(n){const o=["zéro","un","deux","trois","quatre","cinq","six","sept","huit","neuf","dix","onze","douze","treize","quatorze","quinze","seize"];if(n<17)return o[n];if(n<20)return"dix-"+o[n-10];const t={20:"vingt",30:"trente",40:"quarante",50:"cinquante",60:"soixante"};if(n<70){const d=Math.floor(n/10)*10,u=n%10;if(u===0)return t[d];if(u===1)return t[d]+" et un";return t[d]+"-"+o[u]}if(n<80){if(n===71)return"soixante et onze";return"soixante-"+numberToFrench(n-60)}if(n===80)return"quatre-vingts";return"quatre-vingt-"+numberToFrench(n-80)}
function updateProgress(){el.stars.textContent=state.stars;const r=["🌱","🌷","🌳","🦋","🏡","🌈"];el.garden.textContent=r.slice(0,Math.min(Math.floor(state.stars/3)+1,r.length)).join(" ");localStorage.setItem("alice-stars",String(state.stars))}
function addStar(){state.stars++;updateProgress()}
function openScreen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));document.querySelector(`#${id}`).classList.add("active");if(id==="reading")newReadingRound();if(id==="numbers")newNumberRound()}
function shuffled(items){return[...items].sort(()=>Math.random()-.5)}
function newReadingRound(){state.currentSyllable=syllables[Math.floor(Math.random()*syllables.length)];el.readingPrompt.textContent="🔊";el.readingMessage.textContent="";const c=[state.currentSyllable];while(c.length<3){const x=syllables[Math.floor(Math.random()*syllables.length)];if(!c.includes(x))c.push(x)}el.readingChoices.innerHTML="";shuffled(c).forEach(x=>{const b=document.createElement("button");b.className="choice";b.textContent=x;b.addEventListener("click",()=>checkSyllable(x,b));el.readingChoices.appendChild(b)});setTimeout(()=>speak(state.currentSyllable),250)}
function checkSyllable(choice,button){if(choice===state.currentSyllable){button.classList.add("correct");el.readingPrompt.textContent=state.currentSyllable;el.readingMessage.textContent="Bravo ! Une étoile pour toi ⭐";speak(`Bravo ! ${state.currentSyllable}`);addStar();setTimeout(newReadingRound,1400)}else{button.classList.add("wrong");el.readingMessage.textContent="Presque ! Écoute encore.";speak("Presque. Écoute encore.");setTimeout(()=>button.classList.remove("wrong"),700)}}
function buildNumberButtons(){el.tens.innerHTML="";el.units.innerHTML="";for(let n=10;n<=90;n+=10){const b=document.createElement("button");b.className="number-button";b.textContent=n;b.addEventListener("click",()=>{state.selectedTen=n;markSelected(el.tens,b);updateAssembled()});el.tens.appendChild(b)}for(let n=1;n<=9;n++){const b=document.createElement("button");b.className="number-button";b.textContent=n;b.addEventListener("click",()=>{state.selectedUnit=n;markSelected(el.units,b);updateAssembled()});el.units.appendChild(b)}}
function markSelected(container,button){container.querySelectorAll(".number-button").forEach(b=>b.classList.remove("selected"));button.classList.add("selected")}
function clearNumber(){state.selectedTen=null;state.selectedUnit=null;el.assembled.textContent="—";el.numberMessage.textContent="";document.querySelectorAll(".number-button").forEach(b=>b.classList.remove("selected"))}
function newNumberRound(){state.target=(Math.floor(Math.random()*9)+1)*10+(Math.floor(Math.random()*9)+1);el.targetNumber.textContent=state.target;clearNumber();setTimeout(()=>speak(`Construis le nombre ${numberToFrench(state.target)}`),250)}
function updateAssembled(){const value=(state.selectedTen||0)+(state.selectedUnit||0);el.assembled.textContent=value||"—";if(state.selectedTen&&state.selectedUnit){if(value===state.target){el.numberMessage.textContent=`Bravo ! ${numberToFrench(state.target)} ⭐`;speak(`Bravo ! ${numberToFrench(state.target)}`);addStar();setTimeout(newNumberRound,1600)}else{el.numberMessage.textContent="Presque ! Essaie encore.";speak("Presque. Essaie encore.")}}}
document.querySelectorAll("[data-open]").forEach(b=>b.addEventListener("click",()=>openScreen(b.dataset.open)));document.querySelector("#helloBtn").addEventListener("click",()=>speak("Bonjour ! Je suis Alice. Bienvenue dans mon aventure !"));document.querySelector("#resetBtn").addEventListener("click",()=>{state.stars=0;localStorage.removeItem("alice-stars");updateProgress();speak("On recommence l'aventure !")});document.querySelector("#listenSyllableBtn").addEventListener("click",()=>speak(state.currentSyllable));document.querySelector("#listenNumberBtn").addEventListener("click",()=>speak(numberToFrench(state.target)));document.querySelector("#clearNumberBtn").addEventListener("click",clearNumber);buildNumberButtons();updateProgress();if("serviceWorker" in navigator&&location.protocol.startsWith("http")){navigator.serviceWorker.register("service-worker.js").catch(()=>{})}
